### ISSUE TITLE
A JavaDoc {@link ...} directive pointing to a full class name does not produce a link

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frank-doc#117]
If the JavaDoc comments of the F!F contain a {@link ...} directive pointing to the full name of a Java class, then the Frank!Doc website does not produce a link. Instead, the full name of the Java class appears as plain text, without the markup of a link.

Using a {@link ...} with a full class name is a workaround for https://github.com/ibissource/iaf/issues/3196. If that issue is solved, the simple name of the Java class can appear in the {@link ...} and the class can be imported. For that case, the Frank!Doc already shows working links.

**Comment by thomaspj10** [comment]
Tested it and seems to work correctly.
