### ISSUE TITLE
The Frank!Doc may not build without access to our Nexus

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frank-doc#132]
I tried to build the Frank!Doc on my NN laptop. I am doing without a settings.xml file. The build failed with the following message:

```
[ERROR] Failed to execute goal on project frank-doc: Could not resolve dependencies for project org.ibissource:frank-doc:jar:1.1-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.8 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

We have to investigate this issue, because WeAreFrank! is an open-source company. Anyone should be able to build the Frank!Doc.

I have checked that  our Nexus holds artifact com.sun.tools:jar:1.8. As a solution, we may document how to add our Nexus to Maven's settings.xml file before building the Frank!Doc. We may also fix the build by adding our Nexus repository to the Frank!Doc pom.xml.

**Comment by jkosternl** [comment]
Solved by #166
