### ISSUE TITLE
In the webapp, the download button of the Frank!Doc does not work properly

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frank-doc#148]
The web app has a button to download the XSD. If you click it, the XSD is shown in the browser but it is not downloaded. I tried this with Microsoft Edge.

**Comment by nielsm5** [comment]
Volgens mij werkt dit naar behoren, het kan zijn dat wanneer je lokaal draait (zonder frankdoc) het inderdaad niet werkt.

**Comment by mhdirkse** [comment]
Ik heb het ook even gecontroleerd. Het downloaden van de Frank!Doc XSD werkt in frank2example. Terecht dus dat dit issue gesloten is.
