### ISSUE TITLE
Make FrankDocGroup less errorprone

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frank-doc#161]
Right now the FrankDocGroup annotation can be 're-introduced' with the same name but a different 'order' value.
In order to reduce this risk, a fixed set of group entries should be created (using an Enum) with their order.

**Comment by mhdirkse** [comment]
Shall we use the @EnumLabel annotation to set the captions of the Frank!Doc groups? If we do it this way, we do not have to introduce final fields within the enum type. Doing so would be more work because the wrapper API has to be extended.

**Comment by mhdirkse** [comment]
In my proposal, the wrapper API has to be extended to give the order of the enum constants within their type. This is probably a small change.

**Comment by mhdirkse** [comment]
I see that in the wrapper API, a FrankEnumConstant object knows its position within the enum. That is enough if we only make Frank!Doc groups for enum constants that are actually used. Do we want an empty group if there is an enum constant that is never applied?

**Comment by mhdirkse** [comment]
The enum that holds the groups should also have an enum constant for the "Other" group, the default group for FrankElement-s. How do we document in the groups enum which enum constant is for "Other"? I see three options:

* We introduce an annotation for enum constants that we only use on the enum constant for group "Other".
* We give the doclet a new parameter that is set in the pom.xml of the Frank!Framework. That parameter is the enum value used for group "Other".
* We check which enum constants are not applied in explicit @FrankDocGroup annotations. The build fails if there is no such group or if there is more than one. With a succesful build there is thus an unambiguous "Other" group.

I propose to add a new parameter to the doclet anyway - it is the class name of the enum that holds the groups.

**Comment by nielsm5** [comment]
Let's not overcomplicate things for now.
