### ISSUE TITLE
FrankDoc should show deprecation config warnings

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frank-doc#184]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
XmlFileIteratorPipe is deprecated, but the FrankDoc does not show the configuration warning, i.e. with what to replace it. That info is available, however, for instance in the javadoc
See https://frankdoc.frankframework.org/#!/All/XmlFileElementIteratorPipe.
See https://javadoc.frankframework.org/org/frankframework/pipes/XmlFileElementIteratorPipe.html

**Reporter**
Gerrit

**Comment by nielsm5** [comment]
Deprecated text moet in de fronted weergegeven worden

**Comment by nielsm5** [comment]
```
@Deprecated(forRemoval = true, since = "7.6.0")
@ConfigurationWarning("Please replace with ForEachChildElementPipe. ElementName and elementChain can be replaced with containerElement and/or targetElement. It is not a 1 to 1 replacement, different values may be required!")
```

**Comment by thomaspj10** [comment]
Adds the following information to the JSON data:
```json
"deprecated": true,
"deprecationInfo": {
    "forRemoval": true,
    "since": "7.6.0",
    "configurationWarning": "Please replace with ForEachChildElementPipe. ElementName and elementChain can be replaced with containerElement and/or targetElement. It is not a 1 to 1 replacement, different values may be required!"
},
```
These fields can be optional, because not every deprecated class or function has documented these values.

**Comment by philipsens** [comment]
```json
"deprecated": {
    "forRemoval": true,
    "since": "7.6.0",
    "description": "Please replace with ForEachChildElementPipe. ElementName and elementChain can be replaced with containerElement and/or targetElement. It is not a 1 to 1 replacement, different values may be required!"
},
```

**Comment by thomaspj10** [comment]
The metadata will be displayed like this:

![Image](https://github.com/user-attachments/assets/4b363879-2b8f-4eb1-be43-6c06e89b841c)
