### ISSUE TITLE
unclear when literals are used in doc

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frank-doc#231]
literals in doc are not clear in json.
See literal in javadoc:
![image](https://github.com/user-attachments/assets/d75f18e7-aebf-44da-b45c-1968f2536535)

And how it's shown in the json
![image](https://github.com/user-attachments/assets/5b7d60b4-f7d8-4c78-845d-49a3c1a355fa)

`"value": "This is a default job that can be controlled with the property checkReload.active and checkReload.interval."`
Perhaps backticks may be used here?
"value": "This is a default job that can be controlled with the property `checkReload.active` and ``checkReload.interval``.".

**Comment by thomaspj10** [comment]
![Image](https://github.com/user-attachments/assets/e78fbdd9-bde4-41e5-b2a2-588e5a9b78f8)

The literal tag actually doesn't do any formatting. I've implemented it as specified by the [specification](https://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javadoc.html#%7B@literal%7D). "Displays text without interpreting the text as HTML markup or nested javadoc tags.".
